name: Build BIZNIX APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build web app
        run: npm run build

      - name: Add & Sync Android
        run: |
          if [! -d android ]; then
            npx cap add android
          fi
          npx cap copy android
          npx cap sync android

      - name: Build APK Release
        working-directory: android
        run: |
          chmod +x gradlew
         ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BIZNIX-APK
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          if-no-files-found: error